version: '3.8'
services:
  discordbot:
    build: .
    command: node bot.js
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M    # Limit the container to 512 MB of RAM
        reservations:
          memory: 256M    # Reserve 256 MB of RAM for this container