version: '3.8'

services:
  nodeapp:
    build: ./src
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/Audios
      - PUBLIC_TOKEN=${PUBLIC_TOKEN}

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: